@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QzIiwiZW1haWwiOiJqYWtlMkBqYWtlLmpha2UiLCJpYXQiOjE2ODYxMTA4ODJ9.K4eRrfUcq6REIulv_rhXEmGGMKxKwIfD7wp0sXWtTXQ


@token1 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxIiwiZW1haWwiOiJqYWtlMUBqYWtlLmpha2UiLCJpYXQiOjE2MjE4OTA4MDB9.fx5nD6_MjXLPzO-QQswu22HsOwDivI_3-AU0fIoRv64

### 注册
POST /api/users
host: {{host}}
content-type: {{contentType}}

{
  "user":{
    "email": "1063128089@jake.jake",
    "password": "jakejake",
    "username": "test34"
  }
}

### 登录
POST /api/users/login
host: {{host}}
content-type: {{contentType}}

{
  "user":{
    "email": "1063128044@qq.com",
    "password": "huchenxin123"
  }
}

###管理员添加
POST /api/users
host: {{host}}
content-type: {{contentType}}

{
  "user":{
    "email": "1063128034@jake.jake",
    "password": "jakejake",
    "username": "test3"
  }
}


### 查询用户
POST /api/user
host: {{host}}
content-type: {{contentType}}

{
  "user":{
    "email": "1063128044@qq.com"
  }
}


### 删除用户
POST /api/duser
host: {{host}}
content-type: {{contentType}}

{
  "user":{
    "email": "test@qq.com",
    "username":"test1"
  }
}